<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Needle</RootNamespace>
        <IsTrimmable>true</IsTrimmable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Needle.Core.Tests" />
        <InternalsVisibleTo Include="NeedleTests" />
    </ItemGroup>

</Project>
