//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Needle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Needle.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy ....
        /// </summary>
        public static string Label_Busy {
            get {
                return ResourceManager.GetString("Label_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        public static string Label_CaseSensitive {
            get {
                return ResourceManager.GetString("Label_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File mask:.
        /// </summary>
        public static string Label_Filemask {
            get {
                return ResourceManager.GetString("Label_Filemask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subdirectories.
        /// </summary>
        public static string Label_IncludeSubDirectories {
            get {
                return ResourceManager.GetString("Label_IncludeSubDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Label_Regex {
            get {
                return ResourceManager.GetString("Label_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace (in result).
        /// </summary>
        public static string Label_Replace {
            get {
                return ResourceManager.GetString("Label_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string Label_ReplaceWith {
            get {
                return ResourceManager.GetString("Label_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start directory:.
        /// </summary>
        public static string Label_StartDirectory {
            get {
                return ResourceManager.GetString("Label_StartDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start search.
        /// </summary>
        public static string Label_StartSearch {
            get {
                return ResourceManager.GetString("Label_StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string Label_Text {
            get {
                return ResourceManager.GetString("Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Explorer.
        /// </summary>
        public static string Menu_OpenInExplorer {
            get {
                return ResourceManager.GetString("Menu_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Notepad++.
        /// </summary>
        public static string Menu_OpenWithNotepadPlusPlus {
            get {
                return ResourceManager.GetString("Menu_OpenWithNotepadPlusPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found:
        ///{0}.
        /// </summary>
        public static string Msg_FileNotFound {
            get {
                return ResourceManager.GetString("Msg_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad++ is not installed or not found in the system PATH.
        ///
        ///Please install Notepad++ or add it to your PATH environment variable..
        /// </summary>
        public static string Msg_NotepadPlusPlusNotFound {
            get {
                return ResourceManager.GetString("Msg_NotepadPlusPlusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening explorer:
        ///{0}.
        /// </summary>
        public static string Msg_OpenInExplorerError {
            get {
                return ResourceManager.GetString("Msg_OpenInExplorerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file in Notepad++:
        ///{0}.
        /// </summary>
        public static string Msg_OpenNotepadPlusPlusError {
            get {
                return ResourceManager.GetString("Msg_OpenNotepadPlusPlusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle - File Search.
        /// </summary>
        public static string Title_Needle {
            get {
                return ResourceManager.GetString("Title_Needle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad++ Not Found.
        /// </summary>
        public static string Title_NotepadPlusPlusNotFound {
            get {
                return ResourceManager.GetString("Title_NotepadPlusPlusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select start directory.
        /// </summary>
        public static string Title_SelectStartDirectory {
            get {
                return ResourceManager.GetString("Title_SelectStartDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example
        ///Text: (\w+)@(\w+\.com)
        ///Replace with: Email: $1 at domain $2
        ///Input: john@example.com
        ///Output: Email: john at domain example.com.
        /// </summary>
        public static string Tooltip_Regex {
            get {
                return ResourceManager.GetString("Tooltip_Regex", resourceCulture);
            }
        }
    }
}
