//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Needle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Needle.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy ....
        /// </summary>
        public static string Label_Busy {
            get {
                return ResourceManager.GetString("Label_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        public static string Label_CaseSensitive {
            get {
                return ResourceManager.GetString("Label_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File mask:.
        /// </summary>
        public static string Label_Filemask {
            get {
                return ResourceManager.GetString("Label_Filemask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subdirectories.
        /// </summary>
        public static string Label_IncludeSubDirectories {
            get {
                return ResourceManager.GetString("Label_IncludeSubDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in:.
        /// </summary>
        public static string Label_SearchIn {
            get {
                return ResourceManager.GetString("Label_SearchIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File content.
        /// </summary>
        public static string SearchScope_Content {
            get {
                return ResourceManager.GetString("SearchScope_Content", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string SearchScope_FileName {
            get {
                return ResourceManager.GetString("SearchScope_FileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File content and name.
        /// </summary>
        public static string SearchScope_Both {
            get {
                return ResourceManager.GetString("SearchScope_Both", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace in this file.
        /// </summary>
        public static string Tooltip_SelectFile {
            get {
                return ResourceManager.GetString("Tooltip_SelectFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace this match.
        /// </summary>
        public static string Tooltip_SelectMatch {
            get {
                return ResourceManager.GetString("Tooltip_SelectMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        public static string Label_Options {
            get {
                return ResourceManager.GetString("Label_Options", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encoding:.
        /// </summary>
        public static string Label_Encoding {
            get {
                return ResourceManager.GetString("Label_Encoding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encoding for files without byte order mark (BOM)....
        /// </summary>
        public static string Tooltip_Encoding {
            get {
                return ResourceManager.GetString("Tooltip_Encoding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_FileNameMatch {
            get {
                return ResourceManager.GetString("Label_FileNameMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Label_Regex {
            get {
                return ResourceManager.GetString("Label_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace (in result).
        /// </summary>
        public static string Label_Replace {
            get {
                return ResourceManager.GetString("Label_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string Label_ReplaceWith {
            get {
                return ResourceManager.GetString("Label_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start directory:.
        /// </summary>
        public static string Label_StartDirectory {
            get {
                return ResourceManager.GetString("Label_StartDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start search.
        /// </summary>
        public static string Label_StartSearch {
            get {
                return ResourceManager.GetString("Label_StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string Label_Text {
            get {
                return ResourceManager.GetString("Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find in Explorer.
        /// </summary>
        public static string Menu_OpenInExplorer {
            get {
                return ResourceManager.GetString("Menu_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Notepad++.
        /// </summary>
        public static string Menu_OpenWithNotepadPlusPlus {
            get {
                return ResourceManager.GetString("Menu_OpenWithNotepadPlusPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found:
        ///{0}.
        /// </summary>
        public static string Msg_FileNotFound {
            get {
                return ResourceManager.GetString("Msg_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad++ is not installed or not found in the system PATH.
        ///
        ///Please install Notepad++ or add it to your PATH environment variable..
        /// </summary>
        public static string Msg_NotepadPlusPlusNotFound {
            get {
                return ResourceManager.GetString("Msg_NotepadPlusPlusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening explorer:
        ///{0}.
        /// </summary>
        public static string Msg_OpenInExplorerError {
            get {
                return ResourceManager.GetString("Msg_OpenInExplorerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file in Notepad++:
        ///{0}.
        /// </summary>
        public static string Msg_OpenNotepadPlusPlusError {
            get {
                return ResourceManager.GetString("Msg_OpenNotepadPlusPlusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needle - File Search.
        /// </summary>
        public static string Title_Needle {
            get {
                return ResourceManager.GetString("Title_Needle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad++ Not Found.
        /// </summary>
        public static string Title_NotepadPlusPlusNotFound {
            get {
                return ResourceManager.GetString("Title_NotepadPlusPlusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select start directory.
        /// </summary>
        public static string Title_SelectStartDirectory {
            get {
                return ResourceManager.GetString("Title_SelectStartDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example
        ///Text: (\w+)@(\w+\.com)
        ///Replace with: Email: $1 at domain $2
        ///Input: john@example.com
        ///Output: Email: john at domain example.com.
        /// </summary>
        public static string Tooltip_Regex {
            get {
                return ResourceManager.GetString("Tooltip_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Status_Searching {
            get {
                return ResourceManager.GetString("Status_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} matches ({1} files completed).
        /// </summary>
        public static string Progress_Found {
            get {
                return ResourceManager.GetString("Progress_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating UI.
        /// </summary>
        public static string Progress_UpdatingUi {
            get {
                return ResourceManager.GetString("Progress_UpdatingUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Status_Finished {
            get {
                return ResourceManager.GetString("Status_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Status_Canceled {
            get {
                return ResourceManager.GetString("Status_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regex: {0}.
        /// </summary>
        public static string Status_InvalidRegex {
            get {
                return ResourceManager.GetString("Status_InvalidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Status_Error {
            get {
                return ResourceManager.GetString("Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - skipped {0} files and {1} directories (no access or not readable).
        /// </summary>
        public static string Status_Skipped {
            get {
                return ResourceManager.GetString("Status_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected to replace.
        /// </summary>
        public static string Status_NothingSelected {
            get {
                return ResourceManager.GetString("Status_NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing....
        /// </summary>
        public static string Status_Replacing {
            get {
                return ResourceManager.GetString("Status_Replacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced {0} occurrences in {1} files.
        /// </summary>
        public static string Status_Replaced {
            get {
                return ResourceManager.GetString("Status_Replaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement completed with errors. {0} files modified, {1} errors.
        /// </summary>
        public static string Status_ReplacedWithErrors {
            get {
                return ResourceManager.GetString("Status_ReplacedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement canceled.
        /// </summary>
        public static string Status_ReplaceCanceled {
            get {
                return ResourceManager.GetString("Status_ReplaceCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Title_Replace {
            get {
                return ResourceManager.GetString("Title_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace in {0} files?.
        /// </summary>
        public static string Msg_ConfirmReplace {
            get {
                return ResourceManager.GetString("Msg_ConfirmReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace in {0} files?.
        /// </summary>
        public static string Msg_ConfirmReplaceAndRename {
            get {
                return ResourceManager.GetString("Msg_ConfirmReplaceAndRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement Errors.
        /// </summary>
        public static string Title_ReplaceErrors {
            get {
                return ResourceManager.GetString("Title_ReplaceErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred during replacement:.
        /// </summary>
        public static string Msg_ReplaceErrors {
            get {
                return ResourceManager.GetString("Msg_ReplaceErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during replacement:.
        /// </summary>
        public static string Msg_ReplaceError {
            get {
                return ResourceManager.GetString("Msg_ReplaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string Tooltip_SelectFolder {
            get {
                return ResourceManager.GetString("Tooltip_SelectFolder", resourceCulture);
            }
        }
    }
}
